### ISSUE TITLE
Lien "X enregistrements" et bouton "Afficher les enregistrements" identique

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-collectory#1]
Dans la page métadonnée d'un jeux de données (ex : http://portail.gbif.fr/collectory/public/show/in41), le lien et le bouton en haut à droite sont identiques.

Ne serait-il pas mieux de laisser juste le bouton avec un intitulé comme suit : "Afficher les X enregistrements" ?

Si on laisse les deux, il faut traduire l'intitulé du lien

![capture_22](https://cloud.githubusercontent.com/assets/12632799/14641009/881a48f6-0644-11e6-8b14-b5247ede6a2e.PNG)

**Comment by melecoq** [comment]
<img width="357" alt="screen shot 2016-04-28 at 16 28 40" src="https://cloud.githubusercontent.com/assets/3941231/14904628/4cf09944-0d5e-11e6-8a62-645db68b8dc2.png">

J'ai laissé les deux mais j'ai retiré le lien sur 700 160 enregistrements

Fixed on VM-2
