### ISSUE TITLE
[Admin] Lien cassé d'image pour un contact dans une collection

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-collectory#10]
Une image à un lien cassé dans la section d'ajout d'un contact pour une collection
![capture_47](https://cloud.githubusercontent.com/assets/12632799/14666542/62f87d40-06da-11e6-938a-3900598a5201.PNG)

**Comment by melecoq** [comment]
![screen shot 2016-05-02 at 16 17 30](https://cloud.githubusercontent.com/assets/3941231/14970852/6a6f215e-1081-11e6-88a4-49ac7302eaa1.png)

Fixed on VM-2
