### ISSUE TITLE
Page d'accueil des métadonnées - 2ème texte

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-collectory#2]
Mauvaise traduction pour le texte en bas à gauche (sous les catégories)
![capture_23](https://cloud.githubusercontent.com/assets/12632799/14641224/8413f134-0645-11e6-9c42-cb45c0b9a85e.PNG)
![capture_24](https://cloud.githubusercontent.com/assets/12632799/14641226/8415ec1e-0645-11e6-8739-924f0010c7f4.PNG)
![capture_25](https://cloud.githubusercontent.com/assets/12632799/14641227/84161702-0645-11e6-8c5e-c74f322da509.PNG)
![capture_26](https://cloud.githubusercontent.com/assets/12632799/14641225/8415c298-0645-11e6-8e37-bff2b1c2756e.PNG)
![capture_27](https://cloud.githubusercontent.com/assets/12632799/14641223/8413b9c6-0645-11e6-80b7-1db7c94cdb37.PNG)

**Comment by melecoq** [comment]
![screen shot 2016-05-02 at 12 33 50](https://cloud.githubusercontent.com/assets/3941231/14965407/285be6b8-1062-11e6-9541-67d2f16bf74d.png)
![screen shot 2016-05-02 at 12 33 44](https://cloud.githubusercontent.com/assets/3941231/14965406/285a731e-1062-11e6-99f8-87dce3f3888f.png)

Fixed on VM-2
