### ISSUE TITLE
[Admin] Rapport - Rapport d'adhésion vide

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-collectory#22]
La page http://portail.gbif.fr/collectory/reports/membership est vide de toute données ; vu que c'est des intitulés d'institutions Australiennes, je suppose que c'est normal, non ?

![capture_62](https://cloud.githubusercontent.com/assets/12632799/14668440/8c70fe40-06e4-11e6-8a33-9dd1af227db4.PNG)

**Comment by melecoq** [comment]
Oui normal.
