### ISSUE TITLE
[Admin] Rapport - Liens brisés d'image sur la page "Afficher les classifications"

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-collectory#26]
http://portail.gbif.fr/collectory/reports/classification

![capture_65](https://cloud.githubusercontent.com/assets/12632799/14668984/f8a2cb32-06e6-11e6-9c7c-ebc9286ba838.PNG)

**Comment by melecoq** [comment]
Ne pas oublié de mettre le lien ... C'est plus facile ^^

**Comment by melecoq** [comment]
<img width="1182" alt="screen shot 2016-05-02 at 17 08 20" src="https://cloud.githubusercontent.com/assets/3941231/14971593/7e86477e-1088-11e6-8b38-5d83f1b68dd6.png">

Fixed on VM-2
