### ISSUE TITLE
Page d'accueil des métadonnées - 1er texte

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-collectory#3]
Il manque le mot GBIF (en rouge sur la capture d'écran)
![capture_28](https://cloud.githubusercontent.com/assets/12632799/14641312/e7f829ea-0645-11e6-9e71-5381489cf9e9.PNG)

**Comment by melecoq** [comment]
<img width="1122" alt="screen shot 2016-04-28 at 10 56 38" src="https://cloud.githubusercontent.com/assets/3941231/14895890/e6f92b48-0d2f-11e6-92a0-8545e73c381b.png">

En ligne sur la VM-2
