### ISSUE TITLE
[Admin] Rapport - Résultats d'affichage brut

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-collectory#30]
Pour les pages 
- "Afficher les autorisations et droits sur les jeux de données" (http://portail.gbif.fr/collectory/reports/rights)
- "Afficher les paramètres de mobilisation de données" (http://portail.gbif.fr/collectory/ws/dataResource/harvesting)

on a juste les données affichés comme pour un export JSON, sans habillage ni CSS ; est-ce normal ?

P.S : Problème d'accent

![capture_70](https://cloud.githubusercontent.com/assets/12632799/14673251/29378ba0-06fd-11e6-9586-61b909c789de.PNG)
![capture_71](https://cloud.githubusercontent.com/assets/12632799/14673252/2950e38e-06fd-11e6-9dd2-7225f8413372.PNG)

**Comment by melecoq** [comment]
Oui c'est du JSON, c'est un webservice. 
est-ce que tu peux ouvrir un bug "accent" ou on listera les soucis d'accents. Merci
