### ISSUE TITLE
[Admin] Rapport - Page des contacts en double renvoi une erreur

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-collectory#33]
La page "Afficher les contacts en double" (http://portail.gbif.fr/collectory/reports/duplicateContacts) renvoi une erreur inconnu

![capture_72](https://cloud.githubusercontent.com/assets/12632799/14673400/05a23b30-06fe-11e6-91c7-5d6786721d95.PNG)

**Comment by melecoq** [comment]
<img width="1246" alt="screen shot 2016-05-02 at 17 26 59" src="https://cloud.githubusercontent.com/assets/3941231/14971876/70607a18-108b-11e6-849a-3a5678fff8a4.png">

Fixed on VM-2
