### ISSUE TITLE
[Admin] Fil rouge renvoi sur lis-02

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-collectory#39]
Lorsqu'on clique sur "Portail Atlas of Living France " dans le fil rouge

![portail_ala-administration-fil_rouge](https://cloud.githubusercontent.com/assets/12632799/14982402/527559f0-1136-11e6-898a-d527642b87be.PNG)

cela nous envoi sur la page d'accueil du portail de lis-02

![portail_ala-administration-fil_rouge_2](https://cloud.githubusercontent.com/assets/12632799/14982413/61e5f2be-1136-11e6-8bf5-9300f61592fc.PNG)

**Comment by melecoq** [comment]
J'ai modifié et ça renvoit sur portail.gbif.fr qui est pour l'instant encore mon serveur (et non LIS...) mais quand je ferais le basculement des DNS, ça fonctionnera
