### ISSUE TITLE
Page info d'une institution

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-collectory#4]
- titre des diagrammes et critère du diagramme en anglais
- le texte de la section "Collection" (pas tous, seulement, ceux qui ont comme texte une indication)
- voir capture d'écran
  ![capture_30](https://cloud.githubusercontent.com/assets/12632799/14641598/673e0dc2-0647-11e6-9365-10518f3585bb.PNG)
  ![capture_29](https://cloud.githubusercontent.com/assets/12632799/14641600/6808f780-0647-11e6-9e54-ad41db6e1e6c.PNG)

**Comment by melecoq** [comment]
<img width="1187" alt="screen shot 2016-04-28 at 16 30 15" src="https://cloud.githubusercontent.com/assets/3941231/14904642/8305351c-0d5e-11e6-9cee-91d7a58a6c4b.png">

**Comment by melecoq** [comment]
<img width="1220" alt="screen shot 2016-05-01 at 18 54 26" src="https://cloud.githubusercontent.com/assets/3941231/14945859/2917b6b6-0fce-11e6-820f-d6e5bb32f817.png">
<img width="1185" alt="screen shot 2016-05-01 at 18 54 18" src="https://cloud.githubusercontent.com/assets/3941231/14945860/292ca418-0fce-11e6-98aa-efa94801edd4.png">

Fixed on VM-2
