### ISSUE TITLE
Page info d'un jeux de données

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-collectory#5]
- textes, intitulé de lien et autres lignes en anglais (voir captures d'écrans)
- 2ème ligne de la 2ème capture d'écran : rendre la phrase plus 'amicale' (enlever les crochets et parenthèses) ? 
- "Couverture Taxonomique" est un peu trop proche des deux autres sections quand il n'a rien dedans, non ?

![capture_34](https://cloud.githubusercontent.com/assets/12632799/14641982/e9a115e2-0648-11e6-9dd2-699164c56ede.PNG)
![capture_32](https://cloud.githubusercontent.com/assets/12632799/14641983/e9a5f0b2-0648-11e6-85b0-ce3f9731409a.PNG)

**Comment by melecoq** [comment]
![screen shot 2016-05-02 at 16 04 32](https://cloud.githubusercontent.com/assets/3941231/14970638/a1d68526-107f-11e6-8079-6786de993226.png)
![screen shot 2016-05-02 at 16 05 06](https://cloud.githubusercontent.com/assets/3941231/14970643/a91fae70-107f-11e6-80ee-a81bd43d7411.png)
![screen shot 2016-05-02 at 16 05 19](https://cloud.githubusercontent.com/assets/3941231/14970649/b030749c-107f-11e6-9151-be7e15ea2959.png)

Fixed on VM-2
