### ISSUE TITLE
Page d'accueil des jeux de données

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-collectory#6]
- texte en anglais
- proposition de texte
- lien de l'icône cassé
  ![capture_33](https://cloud.githubusercontent.com/assets/12632799/14642465/cfcb85d8-064a-11e6-8f03-8ea49684318d.PNG)

**Comment by melecoq** [comment]
<img width="1169" alt="screen shot 2016-04-20 at 12 28 34" src="https://cloud.githubusercontent.com/assets/3941231/14687600/72df3e7e-06f3-11e6-84d8-56577878537d.png">

Version 1.35 (disponible sur VM)
