### ISSUE TITLE
[Admin] Coordonnées géographique arrondies

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-collectory#8]
Lorsqu'on situe le pointeur ou qu'on renseigne les coordonnées géographique dans un 'objet' de l'administration (collection, institutiton, etc...) ; les coordonnées géographique sont enregistrées mais arrondie

![capture_42](https://cloud.githubusercontent.com/assets/12632799/14666399/a9812984-06d9-11e6-89e6-08dac857b314.PNG)
![capture_43](https://cloud.githubusercontent.com/assets/12632799/14666398/a980dfe2-06d9-11e6-8ead-68c962cdac73.PNG)

**Comment by melecoq** [comment]
Bug corrigé sur 1 partie. La deuxième sera trop compliqué à gérer. (pas urgent)
