### ISSUE TITLE
[Admin] Erreur inconnue lors de l'ajout de la Couverture taxonomique

### ISSUE THREAD

**Issue by CaviereFabien** [gbiffrance/gbiffrance-collectory#9]
Lorsqu'on essaie de renseigner la couverture taxonomique d'une collection puis de mettre à jour
![capture_45](https://cloud.githubusercontent.com/assets/12632799/14666485/fed436ec-06d9-11e6-830d-ea079f0336c8.PNG)
on a l'erreur suivante :
![capture_46](https://cloud.githubusercontent.com/assets/12632799/14666495/0be942f0-06da-11e6-8647-d1b16de381b4.PNG)

**Comment by melecoq** [comment]
![screen shot 2016-05-02 at 16 08 48](https://cloud.githubusercontent.com/assets/3941231/14970711/3a108df0-1080-11e6-9c5e-3989d6a7aab0.png)
![screen shot 2016-05-02 at 16 08 27](https://cloud.githubusercontent.com/assets/3941231/14970712/3a122bba-1080-11e6-9201-9d0de320b4e8.png)

Fixed on VM-2
